### ISSUE TITLE
[Bug] Impossible to get streaming link in Stremio

### ISSUE THREAD

**Issue by DarthVitiate** [LimeDrive/stream-fusion#54]
Good evening, 

**Describe the bug**
Everything is set up, but Stremio isn't able to retrieve any stream link.

Output of the logs:

stream-fusion  | ERROR    | json_response:84 - An error occurred: HTTPSConnectionPool(host='api.real-debrid.com', port=443): Max retries exceeded with url: /rest/1.0/torrents/instantAvailability/a9622705bbaa23ed36e26fbb81e5116b9db290ed/dc3b7cc386c0cdadd7fa3bebaa46d88998b529e5/30e6b85b775aa1e466873bbf6005321082c4dad9/60d1fe6252eb751850c69106e3820d7caf470179/91c71c9ac9e2f6f0ac6ed9c505eff2c4fc15f164/6d52aac614ecefa29137f157b5b0ed1648a8b508/2d70ac06c24f26aefc93330deedd5a66231a6988/cfc00e614a1e471c20b2f261552f343d46efb4dc (Caused by ProxyError('Unable to connect to proxy', NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ffeb781acf0>: Failed to resolve ''http' ([Errno -2] Name does not resolve)")))

stream-fusion  | ERROR    | update_availability:110 - Debrid response is empty : None

**To Reproduce**

Every time for any content.

**Expected behavior**
It should show diferents links from YGG/SW.

**Screenshots**

**Your system info (please complete the following information):**
 - OS: Raspbian
 - Browser Any Desktop APP
 - Version Last
 - Docker :  last docker-compose

**Additional context**

Thank you for your help :)

**Comment by LimeDrive** [comment]
hello, 

check your proxy setting, by default it's warp on the compose stack. ( `http://warp:1080` )

if you don't use proxy, please remove the env from your compose file : 

https://github.com/LimeDrive/stream-fusion/blob/a94b17f7ba87d491a72dae43219903af3d3b0897/deploy/docker-compose.yml#L24

and rebuild your container :

```sh
docker compose rm -s <your_service>
docker compose up -d <your_service>
```

and if the problem persists, clear the redis cache :

```sh
docker exec <your_redis> redis-cli -n 5 flushdb
```

**Comment by DarthVitiate** [comment]
Thank you for helping me.

I used your docker-compose without any modification.
I've followed your instructions and I got this following error log:

![image](https://github.com/user-attachments/assets/04775261-bf4c-461f-b8ed-7e7b54ac95e1)

**Comment by LimeDrive** [comment]
> 

Can you check your Warp container :

docker logs -f warp

**Comment by DarthVitiate** [comment]
UPDATES:

It seems to work WITHOUT de Warp container.

I've tried again including warp and I got this:

![Capture d’écran 2024-10-02 à 01 11 25](https://github.com/user-attachments/assets/bca0ef3e-befb-445b-9524-a3fddf11f045)

**Comment by LimeDrive** [comment]
that's warp proxy issues perhaps.

I run the same version with warp and it's OK on my part.

**Comment by DarthVitiate** [comment]
Yes, it's weird..

I have to figure out why it's working without it.
Should I use a VPN instead?

I really appreciate your help.

**Comment by LimeDrive** [comment]
you don't need it on residential ip. It's for AllDebrid mostly by the way.
more details on how are use the proxy by the addon here : 

https://docs.stremio-stack.com/en/StreamFusion/config_advanced/#proxy-configuration

![image-7spxi-02-10-2024](https://github.com/user-attachments/assets/267f196d-489b-4984-ae43-5d571807fea9)

**Comment by LimeDrive** [comment]
my bad : 
@DarthVitiate 

it's on the compose file :  

replace :
`PROXY_URL: ${PROXY_URL:-'http://warp:1080'}`

by : 
` PROXY_URL: ${PROXY_URL:-http://warp:1080}`

I update on the master.

**Comment by DarthVitiate** [comment]
Thank you so much LimeDrive !!!
Indeed, I didn't notice the " ' ".

It works perfectly!

God bless you.
