### ISSUE TITLE
[Bug] Problème de cache débrideur

### ISSUE THREAD

**Issue by razeNFR** [LimeDrive/stream-fusion#64]
**Describe the bug**
Parfois quand je cherche un film ou une série, TOUT les fichier sont considéré comme n'étant pas en cache sur le débrideur (en l'occurence Real Debrid pour mon cas) alors que si, et quand j'essaye de lire le fichier ça me donne l'erreur "Erreur de lecture" alors que pourtant avant ça fonctionnait bien, j'ai l'impression que ça vient de la dernière update.

**To Reproduce**
Chercher un film/série et essayer de lire un fichier considérer comme pas en cache

**Expected behavior**
Que sois le fichier est déjà en cache et donc considéré comme "instant" sois l'envoyer en download sur le debrideur

**Screenshots**
![image](https://github.com/user-attachments/assets/97611c0b-71d9-4233-9501-3b9ac6b661ff)

**Additional context**
Je ne sais pas si le problème provient de Real Debrid ou pas, mais j'ai essayé avec Alldebrid et c'est pareil, quand j'essaye d'envoyer un torrent en download j'ai l'erreur "Erreur de lecture"

**Comment by razeNFR** [comment]
Friends est un bon exemple pour ce cas, certains épisodes sont considéré en cache alors que d'autre non, alors que pourtant c'est sur la même Saison 3 (pour l'exemple) qui est en un dossier contenant tout les épisodes, donc pourquoi certains épisodes sont considéré en cache et pas d'autres ? 

Ici Episode 25 Saison 3 (considéré pas en cache) :
![image](https://github.com/user-attachments/assets/c7935e54-dfb4-4188-9dff-31f551affb5a)

Ici Episode 17 Saison 3 (le même Torrent mais pas le même episode, qui lui est en cache)
![image](https://github.com/user-attachments/assets/627be723-a910-4846-a18e-95acec97f4d9)

**Comment by LimeDrive** [comment]
Bonjour, 

Peux-tu aller voir les fichiers logs pour avoir le débogage ?  
J'ai déjà eu ce cas avec l'API Real-Debrid, certains endpoints retournent de mauvaises informations (pour le check du cache) et elle a de temps en temps des problèmes de stabilité, je vais tester de mon côté aussi.

**Comment by LimeDrive** [comment]
On n'obtient pas les mêmes résultats car je n'ai pas configuré le 2160p, mais de mon côté, pas de souci.
C'est donc bien un problème côté API de RD
![image-cu98j-25-10-2024](https://github.com/user-attachments/assets/87c78437-6dc1-4279-b3a6-611cdb06ad21)

**Comment by razeNFR** [comment]
> On n'obtient pas les mêmes résultats car je n'ai pas configuré le 2160p, mais de mon côté, pas de souci. C'est donc bien un problème côté API de RD ![image-cu98j-25-10-2024](https://private-user-images.githubusercontent.com/82819873/380117720-87c78437-6dc1-4279-b3a6-611cdb06ad21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTIxODQsIm5iZiI6MTcyOTg1MTg4NCwicGF0aCI6Ii84MjgxOTg3My8zODAxMTc3MjAtODdjNzg0MzctNmRjMS00Mjc5LWIzYTYtNjExY2RiMDZhZDIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDEwMjQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMDdiNTEyOTljNmU2YzEyMTBiNzZkZTU1OGUwOTg4M2EwZGI0MTQ4YjZhYzEzNjM0MmZhZTkzYmE0NDY5NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-5w0nnPo99tbH6SkPF1VyjOWf9N4xwyWoRtxFYLWVVA)

Je viens de relancé la recherche sur l'épisode 25 de la saison 3 et cette fois-ci les épisodes sont bien considéré en cache, mais du coup, comment serait-il possible de résoudre ce problème ? 

Parce que à priori si ça vient de chez Real Debrid c'est à eux de fix le problème c'est ça ?

**Comment by LimeDrive** [comment]
L'instabilité de leur API est souvent passagère, il y a d'ailleurs pour Real-Debrid des limiteurs et du retry déjà en place pour l'éviter au maximum.

Le souci, c'est que sur certains endpoints, par exemple le check de cache, on a quand même un retour vide et pas une erreur.

Je ne peux rien faire pour cela.

De ton côté, tu peux :

- Configurer le service sur la page de configuration utilisateur (donc avec l'authentification de l'application RD) et pas avec le token en variable d'environnement qui a possiblement des limitations plus strictes.

- Configurer en parallèle un compte AllDebrid, comme cela tu seras sûr de toujours avoir le contenu chez l'un ou l'autre, Stream-Fusion agrège automatiquement les résultats et le check de cached.
